FROM registry.redhat.io/devspaces/udi-rhel8:3.1 AS collatz-fe
WORKDIR /src
RUN git clone 'https://github.com/epenedos/Collatz-conjecture.git && cd collatz-fe
RUN go build
 


FROM registry.redhat.io/devspaces/udi-rhel8:3.1 AS collatz-be
WORKDIR /src
RUN git clone 'https://github.com/epenedos/Collatz-conjecture.git && cd collatz-be
RUN go build